### ISSUE TITLE
pad版无法登录

### ISSUE THREAD

**Issue by Narutojoy** [finalpi/wechat2tg#73]
使用dev-pad的docker-compose部署出现问题

- 宿主机：群晖918+
- 系统：6.2.3
- 部署方式：docker-compose
- docker-compose配置
```yaml
version: '3'
services:
  wechat2tg:
    image: finalpi/wechat2tg-pad-dev:latest
    container_name: wx2tg
    volumes:
      - /volume1/docker/wechat_pad/config:/app/storage
      - /volume1/docker/wechat_pad/save-files:/app/save-files # 保存文件夹挂载后贴纸文件不需要重新转换
    # env_file 指定环境变量文件
    env_file: ".env"
    restart: unless-stopped
```

- env配置
```yaml
BOT_TOKEN='token'
API_ID='id'
API_HASH='hash'
ROOM_MESSAGE='<i>🌐#[topic]</i> ---- <b>👤#[(alias)] #[name]: </b>'
OFFICIAL_MESSAGE='<b>📣#[name]: </b>'
CONTACT_MESSAGE='<b>👤#[alias_first]: </b>'
ROOM_MESSAGE_GROUP='<b>👤#[(alias)] #[name]: </b>'
OFFICIAL_MESSAGE_GROUP='<b>📣#[name]: </b>'
CONTACT_MESSAGE_GROUP='<b>👤#[alias_first]: </b>'
CREATE_ROOM_NAME='#[topic]'
CREATE_CONTACT_NAME='#[alias]#[[name]]'
MESSAGE_DISPLAY='#[identity]#[br]#[body]'
BASE_API='http://127.0.0.1:2531/v2/api'
FILE_API='http://127.0.0.1:2532/download'
CALLBACK_API='http://127.0.0.1:3000'
```

- 具体报错
对机器人点击/start从日志里能看到具体chat id
再点击/login就出现下图

![Image](https://github.com/user-attachments/assets/c291c20b-1fbe-4e04-a9fd-a5e2b76a4bda)

貌似是拒绝本机`127.0.0.1`连接？

**Comment by finalpi** [comment]
pad 版需要用到 [Gewechat](https://github.com/Devo919/Gewechat) 容器，CALLBACK_API 需要把 wechat2tg-pad 的 3000 端口映射出来 CALLBACK_API='http://127.0.0.1:3000' 填入 wechat2tg-pad 的 3000 端口作为回调，`BASE_API` `FILE_API` 填 Gewechat 映射出来的端口号
```yaml
version: '3.9'

services:
  gewe:
    image: registry.cn-chengdu.aliyuncs.com/tu1h/wechotd:alpine # 拉取镜像
    container_name: gewe
    ports:
      - "2531:2531"
      - "2532:2532"
    volumes:
      - ./temp:/root/temp
    restart: always
```
